In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [96]:
df = pd.read_csv('heart_disease_uci.csv')
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

# 1. Scatter plot

In [97]:
fig = px.scatter(df, x='age', y='thalch', color='sex', symbol='sex', title='thalch ratio in age').show()

In [98]:
df['e'] = df["age"]/100
fig = px.scatter(df, x='age', y='thalch', color='sex', error_x='e', error_y='e').show()

In [99]:
fig = px.scatter(df, x='age', y='thalch', marginal_x='histogram', marginal_y='rug').show()

In [100]:
fig =  px.scatter(df, x='age', y='thalch', trendline='ols').show()

In [101]:
df = px.scatter(df, x='age', y='thalch', color='sex', title='thalch ratio in age', size='num', hover_data=['num']).show()

# 2. Lineplot

In [102]:
fig_mean = df.groupby('age')['thalch'].mean().reset_index()
fig = px.line(fig_mean, x='age', y='thalch').show()

AttributeError: 'NoneType' object has no attribute 'groupby'

In [ ]:
df = px.data.gapminder().query("continent=='Oceania'")
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
60,Australia,Oceania,1952,69.12,8691212,10039.59564,AUS,36
61,Australia,Oceania,1957,70.33,9712569,10949.64959,AUS,36
62,Australia,Oceania,1962,70.93,10794968,12217.22686,AUS,36
63,Australia,Oceania,1967,71.10,11872264,14526.12465,AUS,36
64,Australia,Oceania,1972,71.93,13177000,16788.62948,AUS,36

In [ ]:
fig = px.line(df, x='year', y='lifeExp', color='country', markers=True).show()

In [ ]:
df = px.data.stocks()
df.head()

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708

In [ ]:
fig = px.line(df, x='date', y='GOOG').show()

# 3. Histogram

In [103]:
dg = pd.read_csv('heart_disease_uci.csv')
dg.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [104]:
fig = px.histogram(dg, x='age').show()

In [107]:
fig = px.histogram(dg, x='slope').show()

In [106]:
fig = px.histogram(dg, x='cp').show()

In [105]:
fig = px.histogram(dg, x='dataset').show()

In [108]:
fig = px.histogram(dg, x='thalch', nbins=20).show()

In [111]:
fig = px.histogram(dg, x='sex', y='thalch', nbins=20, color='sex').show()

In [112]:
fig = px.histogram(dg, x="thalch",
 title='Histogram of thalch',
 labels={'thal':'thal ch'}, # can specify one label per df column
 opacity=0.8,
 log_y=True, # represent bars with log scale
 color_discrete_sequence=['indianred'] # color of histogram bars
 )
fig.show()

In [113]:
fig = px.histogram(dg, x='thalch', color='sex').show()

In [ ]:
fig = px.histogram(dg, x='thalch', y='chol', )